const { app, BrowserWindow } = require('electron')

const createWindow = () => {
  const win = new BrowserWindow({
    width: 800,
    height: 600,
      transparent: false,
    backgroundColor: '#000000ff',
    webPreferences: {
      nodeIntegration: true,
      contextIsolation: false,
    },
    

  })

  win.loadFile('index.html')
}

app.whenReady().then(() => {
  createWindow()
})

const quotes = [
  "Start where you are.",
  "Small steps matter.",
  "Progress over perfection.",
  "Keep going.",
  "One day at a time.",
  "Stay curious.",
  "Do the work.",
  "Learn something today.",
  "Try again tomorrow.",
  "Focus on what you can control.",
  "Simplicity is powerful.",
  "Be patient with yourself.",
  "Growth takes time.",
  "Build, then improve.",
  "Consistency beats intensity.",
  "Think clearly.",
  "Create more than you consume.",
  "Rest is part of progress.",
  "Mistakes are feedback.",
  "Begin before you feel ready.",
  "Stay open to change.",
  "Calm is a strength.",
  "Show up daily.",
  "Make it better, not perfect.",
  "Choose clarity.",
  "Keep learning.",
  "Slow progress is still progress.",
  "Curiosity leads forward.",
  "Effort compounds.",
  "Simple ideas work.",
  "Pay attention.",
  "Trust the process.",
  "Finish what you start.",
  "Ask good questions.",
  "Momentum matters.",
  "Think long term.",
  "Do less, better.",
  "Improvement is a habit.",
  "Build useful things.",
  "Focus brings results.",
  "Start small.",
  "Keep it simple.",
  "Direction matters more than speed.",
  "Learn by doing.",
  "Make space to think.",
  "Discipline creates freedom.",
  "Progress is quiet.",
  "One task at a time.",
  "Make today count.",
  "Don’t rush growth.",
  "Stay consistent.",
  "Adjust as you go.",
  "Solve real problems.",
  "Focus beats motivation.",
  "Effort shows over time.",
  "Keep moving forward.",
  "Learn from yesterday.",
  "Be intentional.",
  "Think clearly, act simply.",
  "Done is better than perfect.",
  "Build skills daily.",
  "Practice makes progress.",
  "Stay grounded.",
  "Use your time wisely.",
  "Keep improving.",
  "Clear goals help.",
  "Focus on fundamentals.",
  "Simple plans work.",
  "Be flexible.",
  "Growth is earned.",
  "Stay present.",
  "Make steady progress.",
  "Learn, adapt, repeat.",
  "Action builds confidence.",
  "Start again if needed.",
  "Choose progress.",
  "Make things better.",
  "Focus on quality.",
  "Improve a little each day.",
  "Build momentum slowly.",
  "Think before acting.",
  "Progress is personal.",
  "Learn from mistakes.",
  "Keep your standards high.",
  "Build with purpose.",
  "Stay disciplined.",
  "Growth follows effort.",
  "Be consistent.",
  "Learn continuously.",
  "Focus creates results.",
  "Keep it practical.",
  "Think long-term.",
  "Improvement is possible.",
  "Show up and try.",
  "Learn something new.",
  "Stay focused.",
  "Build useful habits.",
  "Progress takes patience.",
  "Simplicity scales.",
  "Keep moving."
];
